### ISSUE TITLE
teacher views (Classes) dashboard

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#155]
## Task requirements

Implement the views for the Classes tab of the Teacher dashboard page.
The following endpoints should be made:
- [ ] "Edit details" -> loads up the page to edit class details for the selected class in the table. IMPORTANT: Admin teachers can see all the classes in the school, standard teachers can only see their own.

- [ ] Accept join request -> Teacher accepts the join request of an independent student. Redirects to the form to ensure the student names aren't clashing. Once that form is completed, redirects to the page explaining how that new school student can login.

- [ ] Reject join request -> Teacher rejects the join request of an independent student. Currently redirects to the School tab of the dashboard by default, but it could just redirect to the updated Classes tab or, if possible, just update the table and not "reload" anything at all. 
IMPORTANT: Admin teachers can handle all join requests of the school, standard teachers can only handle those for their own classes.
IMPORTANT: Ensure the email notifications are still sent as they currently are.

- [ ] Create a new class -> Allows teacher to create a new class. Redirects to the new class' Edit Details page. IMPORTANT: Admin teachers can create classes and assign them to other teachers on creation, standard teachers can only create them for themselves.
