### ISSUE TITLE
teacher views (Account) dashboard

### ISSUE THREAD

**Issue by lauracumming** [ocadotechnology/codeforlife-portal-react#156]
## Task requirements

Implement the views for the Account tab of the Teacher dashboard page.
The following endpoints should be made:
- [x] Update account details -> Teacher can update their account details.
- [x] Updating the first name or last name simply reloads the page with a banner saying their update was successful.
- [x] Updating the password logs the user out and prompts them to re-login with their new password.
- [ ] Updating the email address logs the user out and asks them to verify the new email (the user can still login with the old email). IMPORTANT: There is a bug on the website currently where the two emails generated from changing the email are sent to the old email address; the expected behaviour is that one should be sent to the old address and one to the new address. Make sure this is the case in the new system.

- [x] Two factor authentication: DO NOT IMPLEMENT THIS IN THIS TASK. This is a separate task - cf Miro or ask team.

- [x] Delete account -> Allows teacher to delete their account. Warns them that their students and classes will be deleted if they haven't transferred them prior to deleting the account.
