### ISSUE TITLE
Email verification reminder

### ISSUE THREAD

**Issue by faucomte97** [ocadotechnology/codeforlife-portal-react#98]
## Task Description
We want to send out a email verification reminder to users who have registered but not verified their email after a week's gone by.

## Acceptance Criteria
- [ ] Create the new email verification email object
---------------------------------------------------------------------------------------------------------------------------------
- [ ] Write a script / endpoint which:
- [ ] Isolates users who have registered over a week ago and still haven't verified their emails
- [ ] Creates a new verification link for these users
- [ ] Sends out the new verification email to these users
---------------------------------------------------------------------------------------------------------------------------------
- [ ] Create a scheduled job in GCP which runs every day and calls that script / endpoint.
- [ ] Each user should only receive the reminder once however, so we will need to track which ones have received the reminder already and exclude them for any future scheduled jobs.

Testing: We will need to test this on dev instead of staging so we don't block the deployment pipeline for over a week.

### Analytics Requirements
- [ ] We could track how often the reminders get sent out (TBD)

### Copywrite Requirements
- [ ] https://docs.google.com/document/d/1RnGRN5UN3pkJmRKCv3WEXvL8SNeLjE25ms7asCCfCJ4/edit
